### ISSUE TITLE
Primus is pointing to window.document.location.host

### ISSUE THREAD

**Issue by xibaca** [xmpp-ftw/skeleton-project#3]
It doesn't work at first, unless we change it to 'https://xmpp-ftw.jit.su'.

**Comment by lloydwatkin** [comment]
That's by design, you need to be running the server for this to work.

**Comment by xibaca** [comment]
There should be a warning for people that clone this project and attempt to run it locally, imho.

**Comment by lloydwatkin** [comment]
Isn't that what this covers: https://github.com/xmpp-ftw/skeleton-project#setup ?

If it could be clearer please let me know.

**Comment by xibaca** [comment]
I just pointed this out because I tried following exactly these steps and it didn't work. Only after we did the change above, we could manage to start doing things with xmpp-ftw.
But maybe this is because my server was running localhost within a VirtualBox? (my host machine has access to it)

**Comment by lloydwatkin** [comment]
I can't see how that would be an issue right now. Maybe it is something to
do with your set up though. Several people have tried the project and had
no issues. That said I'll give it a quick try tomorrow and confirm.

**Comment by xibaca** [comment]
I know that @vitoravelino was having an issue as well, I'm guessing it was the same problem.

**Comment by lloydwatkin** [comment]
This has been fixed. All code was using the latest **1.x** releases of the modules but a slightly older 1.x release of `xmpp-ftw` which didn't understand the stanza ID spoofing code. I _knew_ I should have gone with a major version bump, oh well! All working now.
